[build-system]
requires = ["setuptools==68.2.2", "wheel==0.41.2"]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
addopts = ["--cov=ktl", "--cov-report=term-missing"]
testpaths = ["tests"]

[tool.pylint.'MESSAGES CONTROL']
max-line-length = 120
disable = ["E0401"]
