name: Build sphinx docs

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [ '3.12' ]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.os }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.os }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip;
          pip install -r requirements_dev.txt;
      - name: Generate documentation
        run: |
          sphinx-apidoc -o docs/source src/ktl
      - name: Build HTML
        run: |
          cd docs/
          make html
#      - name: Run ghp-import
#        run: |
#          ghp-import -n -p -f docs/build/html
